version: 2
jobs:
  build:
    ignore:
        - gh-pages
    docker: # use the docker executor type; machine and macos executors are also supported
        - image: circleci/node:10
    environment:
        - SOURCE_BRANCH: master
    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
            name: Install dependencies
            command: npm install
      
      - run: npm rebuild node-sass

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
            name: Build
            command: npm run build

      - run:
          name: Deploy Master to Heroku
          command: |
            heroku login
            me@piyushmehta.com
            piyush_mehta24
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

