version: 2
jobs:
  build:
    ignore:
        - gh-pages
    docker: # use the docker executor type; machine and macos executors are also supported
        - image: circleci/node:10
    environment:
        - SOURCE_BRANCH: master
        - TARGET_BRANCH: gh-pages
    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
            name: Install dependencies
            command: npm install
      
      - run: npm rebuild node-sass

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
            name: Build
            command: npm run build


