version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
        - image: circleci/node:8 
    steps:
      - checkout # check out the code in the project directory
      - run: npm i # npm i for install dependencies
      - run: npm run build # run the build
